### ISSUE TITLE
How to Un-differencing the data?

### ISSUE THREAD

**Issue by shenxiangzhuang** [jinit24/ARIMA-Model#1]
Hello Jinit, I have read your awesome code in this repo and the article in [medium](https://medium.com/analytics-vidhya/arima-model-from-scratch-in-python-489e961603ce) which helps me a lot and thank you for your work. But I can not grasp the key idea about the way of Un-differencing the data. Could you please explain the code with more details?
```python
df_c.Value += np.log(df).shift(1).Value
df_c.Value += np.log(df).diff().shift(12).Value
df_c.Predicted_Values += np.log(df).shift(1).Value 
df_c.Predicted_Values += np.log(df).diff().shift(12).Value
df_c.Value = np.exp(df_c.Value)
df_c.Predicted_Values = np.exp(df_c.Predicted_Values)
```

**Comment by jinit24** [comment]
The differencing is done using  : 
```python3
pd.DataFrame(np.log(df.Value).diff().diff(12))

```

So if the differencing was just shift(1), you'd add only the shift(1).value  (This was the value that was removed)
But now that we are differencing twice, you have to add the shift(1), then the shift(1) shifted by 12.

**Comment by shenxiangzhuang** [comment]
Sorry for my late reply, and I try to figure out the transformation by these equations as fellows, which I think may help others in a way~
![image](https://user-images.githubusercontent.com/17157965/126991946-bb74ef2e-af5b-42da-82cd-b5a6dc147416.png)
